CC=g++
Flags= -Wall -ggdb 


#all: autogui
#
#autogui: main.o
#	g++ -ggdb main.o -o autogui
#
#main.o: main.cpp
#	g++ -ggdb -c main.cpp
#

all: 
	${CC} ${Flags} *.cpp -o autogui -lpthread
clean:
	rm -f autogui
